// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvy_-voC4ZsICsFQop_xVGuDiyTK_Wonk',
    appId: '1:588172701499:android:28c8faf04a70d0b06cd11e',
    messagingSenderId: '588172701499',
    projectId: 'vishwapreneur-1767c',
    databaseURL: 'https://vishwapreneur-1767c.firebaseio.com',
    storageBucket: 'vishwapreneur-1767c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0UJBaz2fhpDh68wNTvv9aCDHY4r2wxiM',
    appId: '1:588172701499:ios:9fa48bb68fa019e36cd11e',
    messagingSenderId: '588172701499',
    projectId: 'vishwapreneur-1767c',
    databaseURL: 'https://vishwapreneur-1767c.firebaseio.com',
    storageBucket: 'vishwapreneur-1767c.appspot.com',
    androidClientId: '588172701499-rjvvgfj7kvkvb453e07qp0akdgkmcqg6.apps.googleusercontent.com',
    iosClientId: '588172701499-vmimrt1puv4htc9usb3llfcol32gt9c8.apps.googleusercontent.com',
    iosBundleId: 'in.vishwapreneur.admin',
  );
}
